### ISSUE TITLE
Typos in the code

### ISSUE THREAD

**Issue by HamadYA** [hekaijie123/TATrack#10]
Hi,
Thanks for the great repo.

I think you have a typo TATrack/experiments/tatrack/test/tiny/got.yaml
line 48
pretrain_model_path: "epoch-59.pkl"
should be
pretrain_model_path: "tiny.pkl"

line 69
device_num: `
should be
device_num: 1

**Comment by hekaijie123** [comment]
Thanks for pointing out that our code may have some roughness.
