### ISSUE TITLE
Evaluation of data sets

### ISSUE THREAD

**Issue by Clarkwk** [hekaijie123/TATrack#11]
Hello, do you have your own evaluation documents, or what do you use for evaluation?

**Comment by hekaijie123** [comment]
Run files such as experiments/tatrack/test/tiny/got.yaml to test the dataset. Some datasets provide annotations, such as LaSOT, to generate offline results. Some datasets must be evaluated online and require local prediction results to be uploaded to the official website for evaluation, such as GOT,TrackingNet.
