### ISSUE TITLE
Test other dataset

### ISSUE THREAD

**Issue by JornyWan** [hekaijie123/TATrack#13]
What should i modify if i want to test VOT2022 or VOT2023 dataset? 
I found that you have some methods to change the groundtruth file format from VOT to the specified format that the algorithm can use and found that you have set VOT2016--2019 dataset in eao_benchmark, when i modify a yaml file in experiments like change tester name to "VOTTester", i received the following error: (I want to test vot2023 dataset)
d_coerce_cfg_value_type
    raise ValueError(
ValueError: Type mismatch (<class 'yacs.config.CfgNode'> vs. <class 'str'>) with values (VOT2018: datasets/VOT/vot2018
VOT2019: datasets/VOT/vot2019 vs. /Users/jorny/docu_gatech/votcmu/vot2023/vots2023-old) for config key: test.track.tester.VOTTester.data_root

**Comment by Alan-HuangKP** [comment]
same question, I wanna test on OTB100, how can I rewrite the test ymal. Looking forward to your reply!

**Comment by hekaijie123** [comment]
Sorry, the code framework is supported up to VOT2018. higher versions need to be ported by yourself.

**Comment by hekaijie123** [comment]
Hellow. Only the last part of yaml needs to be changed.
Reference experiments/tatrack/test/tiny/otb.yaml

    tester:
      names: ["OTBTester",]
      OTBTester:
        exp_name: *TEST_NAME
        exp_save: *TEST_SAVE
        subsets: [ "otb2015" ]
        device_num: 1

________________________________
