### ISSUE TITLE
训练时分类损失的问题

### ISSUE THREAD

**Issue by chenyou203** [hekaijie123/TATrack#19]
在训练过程中，分类损失先急速下降，又上升，又缓慢下降，请问这种现象是正常的？
![image](https://github.com/hekaijie123/TATrack/assets/77626399/2d9dd624-83e2-429d-b2d6-8cdcaa41c329)

**Comment by hekaijie123** [comment]
正常。这是那个分类损失函数的特性，可以去看看引用的文章。
________________________________
From: Chen You ***@***.***>
Sent: Wednesday, January 10, 2024 11:09
To: hekaijie123/TATrack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hekaijie123/TATrack] 训练时分类损失的问题 (Issue #19)


在训练过程中，分类损失先急速下降，又上升，又缓慢下降，请问这种现象是正常的？
image.png (view on web)<https://github.com/hekaijie123/TATrack/assets/77626399/2d9dd624-83e2-429d-b2d6-8cdcaa41c329>

―
