### ISSUE TITLE
请问可以提供一下你们的训练日志吗

### ISSUE THREAD

**Issue by chenyou203** [hekaijie123/TATrack#20]
请问可以提供一下你们的tensorboard训练日志吗

**Comment by hekaijie123** [comment]
没有了哥。毕业了，谁还想保留那些痛苦的东西，实验室的服务器也要求清理遗物。就算还有训练日志也没什么参考价值，深度学习不固定种子多跑几次，每次都不一样。
________________________________
From: Chen You ***@***.***>
Sent: Wednesday, March 20, 2024 9:14
To: hekaijie123/TATrack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hekaijie123/TATrack] 请问可以提供一下你们的训练日志吗 (Issue #20)


请问可以提供一下你们的tensorboard训练日志吗

―

**Comment by chenyou203** [comment]
阿这，好吧，谢了哥

**Comment by hekaijie123** [comment]
想要SOTA多把最新的SOTA模块融进来，然后多调参。祝好

________________________________
