### ISSUE TITLE
图一气泡图

### ISSUE THREAD

**Issue by ElliottZhen** [hekaijie123/TATrack#21]
你好作者，请问图一的气泡图怎么画，是用代码还是wps，请问如何只显示气泡的坐标，非常感谢。

**Comment by hekaijie123** [comment]
Matplotlib就可以画，但是要画的好看需要咨询一下GPT。我当时用的方法很蠢，手工在Drawio画的，尺寸刻度也是手动算出来的，很繁琐。

________________________________
From: wanzhen ***@***.***>
Sent: Tuesday, April 9, 2024 16:36
To: hekaijie123/TATrack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hekaijie123/TATrack] 图一气泡图 (Issue #21)


你好作者，请问图一的气泡图怎么画，是用代码还是wps，请问如何只显示气泡的坐标，非常感谢。

―

**Comment by ElliottZhen** [comment]
非常感谢您这么快回复
