### ISSUE TITLE
About “Download the models we trained”

### ISSUE THREAD

**Issue by YangMinbobo** [hekaijie123/TATrack#3]
Hello，
    I am doing an experiment on target tracking recently. I think your article is very good. I want to use this article to improve my practical ability. But during the operation, there is a problem that there is no model. I see that you write in readme that you need to download. Can you provide a link to download this model? Thank you.

**Comment by hekaijie123** [comment]
https://drive.google.com/drive/folders/1PqiciVkwmtD9VCRkHVhZLsLA6cuz5oF1?usp=share_link
