### ISSUE TITLE
raise TypeError("Invalid shape {} for image data")

### ISSUE THREAD

**Issue by cezeribursa** [hekaijie123/TATrack#6]
I changed as true visualize parameter in got10k.py in order to see whats going on. But viz.py gives raise TypeError("Invalid shape {} for image data" from matplotlib. shape is (3,512,640). i looked on google so it supposed to be like (512,640,3). am i wrong on that one, or i am just having this format for no reason ?

**Comment by cezeribursa** [comment]
Also its just works if i give the actual image's matris rather than tensored images

**Comment by hekaijie123** [comment]
This part is not clear to me. This code is modified based on previous frameworks, and I write some temporary code where needed when using visualization, but it is not integrated into this framework. If you need visualization, you can write it where you need it. This should be relatively simple, and you can check the web for methods.
