### ISSUE TITLE
question about template feature and previous feature through backbone again

### ISSUE THREAD

**Issue by faicaiwawa** [hekaijie123/TATrack#9]
thanks for your great work again ！ Can you help me answer my question, Is it necessary to use the previous frame features and template frame features extracted by backbone again when used for new search frame inference ？  why can't they be directly concated with the search frame features  ?

中文：再次感谢你的工作！为什么经过backbone提取过后的历史帧特征和模板帧特征，在用于新的搜索帧推理时需要再次通过backbone？直接拿来和搜索帧特征concate到一起不可以吗？是效果不好吗

**Comment by hekaijie123** [comment]
New image combinations have a different focus of search frames when they are fused through the backbone. It is better to recalculate.
